name: Showcase Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - website/src/data/**

permissions:
  contents: read

jobs:
  validate-config:
    name: Validate Showcase Config
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
      - name: Set up Node
        uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # v3
        with:
          node-version: '16'
          cache: yarn
      - name: Installation
        run: yarn
      - name: Test
        run: yarn test website/src/data/__tests__/user.test.ts
